### ISSUE TITLE
SINTESIS

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-3-sintesis-Sandoval6#2]

**Comment by Sandoval6** [comment]
[SINTESIS_CHARLY.pdf](https://github.com/user-attachments/files/16841074/SINTESIS_CHARLY.pdf)

**Comment by luzm23** [comment]
Calificacion:18/20

**Comment by josealfredo79** [comment]
Faltan las referencias. la calificacion es de 18...favor de calificar objetivamente @luzm23
